-- GitHub Dark Colorblind. Generated by tools/make-github-themes from
-- @primer/primitives@11.10.0. Do not hand-edit.
--
-- Every number below is a Primer token rather than a taste. GitHub publishes
-- its border widths, its corner radii, its elevation shadows and -- the part
-- that matters most here -- its five easing curves, each with a written note
-- saying which kind of motion it is for. Those notes are quoted verbatim
-- beside the curves, because they are the reason each one is used where it is.

-- --borderWidth-thick (2px). GitHub draws a resting border at 1px and a
-- focused one at 2px; Hyprland has one width for both states, so the width
-- taken is the focus width and the colour carries all the state. Stated here
-- rather than quietly rounded away.
local BORDER = 2

-- --borderRadius-medium (6px), which Primer also aliases as
-- --borderRadius-default: "preferred default border radius for standard UI
-- components". A window is a standard UI component.
local RADIUS = 6

local active_border = "rgba(1f6febff)"    -- --borderColor-accent-emphasis, the focus ring
local inactive_border = "rgba(3d444dff)"  -- --borderColor-default

hl.config({
  general = {
    border_size = BORDER,
    col = {
      active_border = active_border,
      inactive_border = inactive_border,
    },
    resize_on_border = true,
  },

  group = {
    col = {
      border_active = active_border,
      border_inactive = inactive_border,
    },
  },

  decoration = {
    rounding = RADIUS,

    -- --shadow-floating-small, minus its `0 0 0 1px` layer. That layer is a
    -- border drawn as a shadow so it survives a layout shift; Hyprland has a
    -- real border and does not need the trick.
    shadow = {
      enabled = true,
      range = 18,
      render_power = 2,
      offset = "0 6",
      color = "rgba(01040966)",
    },

    -- GitHub is a document, and you cannot see through a document. There is
    -- no blur token in Primer because there is no blur in the product.
    blur = { enabled = false },

    -- No dim either. GitHub never dims a page for being unfocused -- it has
    -- --bgColor-disabled for controls that cannot be used, and an unfocused
    -- window is not a disabled one.
    dim_inactive = false,
  },

  animations = { enabled = true },
})

-- Primer's easing curves, transplanted whole. A CSS cubic-bezier and a
-- Hyprland bezier are the same four numbers in the same order, so these are
-- not approximations of GitHub's motion -- they are GitHub's motion.
--
--   ghEase       "CSS default easing. Use for hover state changes and
--                 micro-interactions."
--   ghEaseIn     "Accelerating motion. Use for elements exiting the viewport."
--   ghEaseOut    "Decelerating motion. Use for elements entering the viewport
--                 or appearing on screen."
--   ghEaseInOut  "Smooth acceleration and deceleration. Use for elements
--                 moving or morphing within the viewport."
hl.curve("ghEase", { type = "bezier", points = { { 0.25, 0.1 }, { 0.25, 1.0 } } })
hl.curve("ghEaseIn", { type = "bezier", points = { { 0.7, 0.1 }, { 0.75, 0.9 } } })
hl.curve("ghEaseOut", { type = "bezier", points = { { 0.3, 0.8 }, { 0.6, 1.0 } } })
hl.curve("ghEaseInOut", { type = "bezier", points = { { 0.6, 0.0 }, { 0.2, 1.0 } } })

-- Durations are --base-duration-100 and --base-duration-200. Hyprland counts
-- animation speed in deciseconds, so 200ms is 2.0 and 100ms is 1.0, and no
-- number here was chosen by watching it and deciding it felt about right.
hl.animation({ leaf = "global", enabled = true, speed = 2.0, bezier = "ghEaseOut" })

-- A window arriving is an element entering the viewport, and a window leaving
-- is an element exiting it. Primer has a separate curve for each and is very
-- clear about which is which, so they do not share one.
hl.animation({ leaf = "windows", enabled = true, speed = 2.0, bezier = "ghEaseOut" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2.0, bezier = "ghEaseOut", style = "popin 92%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.0, bezier = "ghEaseIn", style = "popin 92%" })

-- Workspaces move within the viewport rather than entering or leaving it,
-- which is the case easeInOut is written for.
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.0, bezier = "ghEaseInOut", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 2.0, bezier = "ghEaseInOut", style = "slidevert" })

-- Menus, the launcher and notifications are overlays appearing on screen.
hl.animation({ leaf = "layers", enabled = true, speed = 1.0, bezier = "ghEaseOut", style = "fade" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.0, bezier = "ghEase" })
hl.animation({ leaf = "border", enabled = true, speed = 1.0, bezier = "ghEase" })

-- No spinning gradient border. GitHub does not have one of those.
hl.animation({ leaf = "borderangle", enabled = false })

-- Group tabs are GitHub's file tabs, and GitHub marks the tab you are on with
-- a 2px orange rule underneath it -- --underlineNav-borderColor-active, the
-- one warm colour in an otherwise entirely blue interface. It is the single
-- most recognisable pixel in the product and it costs two lines to have.
hl.config({
  group = {
    groupbar = {
      font_family = "monospace",
      font_size = 12,
      font_weight_active = "bold",
      font_weight_inactive = "normal",
      height = 20,
      indicator_height = 2,
      indicator_gap = 4,
      gradients = false,
      text_color = "rgb(f0f6fc)",
      text_color_inactive = "rgb(9198a1)",
      col = {
        active = "rgba(f78166ff)",
        inactive = "rgba(151b23ff)",
      },
    },
  },
})

-- Gaps and per-window opacity are left to you. This file loads before
-- ~/.config/hypr/looknfeel.lua, so everything above is an opening offer.
