[polkit]
background       = "#070c18"
background-alpha = 0.98
text             = "#e6eaf2"
text-error       = "#ff8b7a"
border           = "hyprland.active-border"
border-error     = "#ff8b7a"
border-alpha     = 1.0
scrim            = "#010206"
scrim-alpha      = 0.66
accent           = "#cfe0f5"
