# GitHub's dropdown menu, same construction as the command palette.
[menu]
background                = "#010409"
background-alpha          = 1.0
text                      = "#ffffff"
border                    = "#b7bdc8"
border-alpha              = 1.0
scrim                     = "#d1d7e0"
scrim-alpha               = 0.4
selected-background       = "#151b23"
selected-background-alpha = 1.0
selected-text             = "#74b9ff"
selected-border           = "#409eff"
selected-border-alpha     = 1.0
